### PR TITLE
Do not expose the hostname to the server, just make it localhost

### PR DESCRIPTION
**Pull request by Hocuri**
I run the dc python remote tests on this and, no surprise, they ran fine.
Fix https://github.com/async-email/async-smtp/issues/25 fix https://github.com/deltachat/deltachat-core-rust/issues/1728

### CODE REVIEW

**Comment by dignifiedquire** [comment]
Can you please test with the major email providers, that this does not result in any blocks? There are some references that if this hostname is incorrect, it can result in spam blockages.

**Comment by Hocuri** [comment]
I'll do this but isn't the hostname just some random name the user or the vendor chose?

**Comment by dignifiedquire** [comment]
> I'll do this but isn't the hostname just some random name the user or the vendor chose?

It is not, it is supposed to be a dns name that resolves to the public IP of the sender, or the actual public IP.

**Comment by Hocuri** [comment]
I tested with Gmail, Yahoo and Posteo now and all worked fine. Is this enough?

**Comment by dignifiedquire** [comment]
> I tested with Gmail, Yahoo and Posteo now and all worked fine. Is this enough?

Seems reasonable, if we run into issues we can change it again

**Pull request merged**
