### PR TITLE
Update fast-socks5 dependency

### PR DESCRIPTION
**Pull request by amaurym**

### CODE REVIEW

**Comment by amaurymartiny** [comment]
Gentle ping on this PR 🙏

**Review by flub — APPROVED** [review]

**Comment by mre** [comment]
@dignifiedquire can we merge this? It's currently blocking the homebrew release of [lychee](https://github.com/lycheeverse/lychee). 😕

**Review by dignifiedquire — APPROVED** [review]

**Comment by amaurym** [comment]
Thanks @dignifiedquire, any chance we can get a 0.3.5?

**Comment by mre** [comment]
Yup, a new 0.3.5 release would be mega @dignifiedquire. Sorry for being so pushy, but our downstream crates depend on it for their next releases. 😅

**Comment by dignifiedquire** [comment]
finally got around to publishing `0.4.0`

**Comment by mre** [comment]
Thanks!

**Pull request merged**
